### ISSUE TITLE
Scraping error

### ISSUE THREAD

**Issue by kennyelliott** [indutny/eve-market#1]
It looks like the last update to the api broke this/

It's a shame too. I found this very useful.

Any chance this is an easy fix?

Error: Max retries reached for: /regions/
    at request.limiter.call [as _onTimeout](/home/kenny/EveTools/eve-market/lib/market/scraper.js:91:23)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by kennyelliott** [comment]
Turns out CCP changed the host name of the public crest server.

I've submitted a pull request with this change.
